name: manetabi_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  bottom_bar_with_sheet: ^2.4.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  icon_decoration: ^2.0.2
  intl: ^0.18.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # テスト用画像フォルダ
  assets:
    - assets/images/

  # フォント
  fonts:
    - family: HiraginoMaruGothicPro
      fonts:
        - asset: assets/fonts/hiragino_maru_gothic_pro/hiragino-maru-gothic-pro-w4.otf
    - family: JockeyOne
      fonts:
        - asset: assets/fonts/jockey_one/JockeyOne-Regular.ttf
